name: Publish and release

on:
  repository_dispatch:
    types:
      - release-triggered

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - id: publish
        run: scripts/ci/release.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTOMATION_TOKEN}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.publish.outputs.version }}
          release_name: Release v${{ steps.publish.outputs.version }}
          body: ${{steps.publish.outputs.notes}}
          draft: false
          prerelease: false
